name: test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: touch foo.snap
      - run: md5sum foo.snap

      - name: Upload snap artifact
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: '*.snap'